import { ArrowUpRight, Clock3, FileText, MoreHorizontal, Plus, TrendingUp, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

const decisions = [{ title: 'Q3 platform pricing strategy', owner: 'Maya Chen', status: 'In review', date: 'Today, 10:42 AM', tone: 'orange' }, { title: 'Enterprise onboarding sequence', owner: 'Julian Park', status: 'Approved', date: 'Yesterday', tone: 'green' }, { title: 'Remote work policy refresh', owner: 'Noah Williams', status: 'Draft', date: 'Aug 22, 2024', tone: 'gray' }]

export default function Overview() {
  const { user } = useAuth()
  const firstName = user?.full_name?.split(' ')[0]
  return <><div className="overview-head"><div><p className="eyebrow">WEDNESDAY, AUGUST 28, 2024</p><h1>Good morning, {firstName}.</h1><p className="intro-text">Here is the signal across your decision workspace.</p></div><Link to="/decisions/new" className="button button-orange"><Plus size={16} /> New decision</Link></div><div className="metric-grid"><div className="metric-card highlight"><span className="metric-label">Active decisions <TrendingUp size={15} /></span><strong>18</strong><small><b>+12.5%</b> from last month</small><div className="mini-chart"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="metric-card"><span className="metric-label">Awaiting your review <Clock3 size={15} /></span><strong>06</strong><small><b className="ink-text">3 due today</b> · Keep things moving</small></div><div className="metric-card"><span className="metric-label">Team participation <Users size={15} /></span><strong>84<sup>%</sup></strong><small><b>+4.2%</b> vs. last quarter</small></div></div><section className="decision-section"><div className="section-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h2>Recent decisions</h2></div><Link to="/decisions" className="view-all">View all <ArrowUpRight size={15} /></Link></div><div className="decision-table"><div className="table-head"><span>Decision</span><span>Owner</span><span>Status</span><span>Last activity</span><span /></div>{decisions.map((decision) => <div className="table-row" key={decision.title}><div className="decision-name"><span className="file-icon"><FileText size={16} /></span><b>{decision.title}</b></div><span className="owner"><span className="tiny-avatar">{decision.owner.split(' ').map((part) => part[0]).join('')}</span>{decision.owner}</span><span className={`status status-${decision.tone}`}><i />{decision.status}</span><span className="date">{decision.date}</span><button className="more-button" aria-label="More options"><MoreHorizontal size={17} /></button></div>)}</div></section></>
}
