"""Add due_date and email_notifications_enabled

Revision ID: 0e1bdf5af37e
Revises: 0003_documents_and_escalation
Create Date: 2026-10-04 22:16:06.443948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1bdf5af37e'
down_revision: Union[str, Sequence[str], None] = '0003_documents_and_escalation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approvals', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('approvals', 'reminder_sent_at')
    op.drop_column('approvals', 'due_date')
    # ### end Alembic commands ###
