const params=new URLSearchParams(location.search);const decisionId=params.get("id");let current=null;
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function msg(t,type="success"){const a=document.getElementById("alert");a.textContent=t;a.className="alert "+type;a.style.display="block";setTimeout(()=>a.style.display="none",3500)}
async function loadAll(){const [a,docs,comments,versions]=await Promise.all([apiRequest(`/decisions/${decisionId}/alternatives`,{},true),apiRequest(`/documents/decision/${decisionId}`,{},true),apiRequest(`/decisions/${decisionId}/discussions`,{},true),apiRequest(`/decisions/${decisionId}/versions`,{},true)]);document.getElementById("alternatives").innerHTML=a.length?a.map(x=>`<article class="alt-card"><div class="alt-head"><h3>${esc(x.title)}</h3><button class="icon-danger" onclick="delAlt(${x.id})">×</button></div><p>${esc(x.description||"No description")}</p><div class="alt-meta"><span><b>Pros</b>${esc(x.pros||"—")}</span><span><b>Cons</b>${esc(x.cons||"—")}</span><span><b>Cost</b>${x.estimated_cost??"—"}</span><span><b>Feasibility</b>${esc(x.feasibility||"—")}</span><span><b>Risk</b>${esc(x.risk||"—")}</span></div></article>`).join(""):'<div class="empty">No alternatives yet. Add the options you are considering.</div>';document.getElementById("documents").innerHTML=docs.length?docs.map(x=>`<div class="file-row"><span>▣</span><div><b>${esc(x.original_filename)}</b><small>${Math.round((x.file_size||0)/1024)} KB · uploaded by ${esc(x.uploader_name)}</small></div><a class="table-btn" target="_blank" href="${API_BASE_URL}/documents/${x.id}/download">Download</a><button class="icon-danger" onclick="delDoc(${x.id})">×</button></div>`).join(""):'<div class="empty">No supporting documents uploaded.</div>';document.getElementById("comments").innerHTML=comments.length?comments.map(x=>`<div class="comment"><div class="avatar">${esc(x.author_name[0])}</div><div><b>${esc(x.author_name)}</b><small>${new Date(x.created_at).toLocaleString()}</small><p>${esc(x.comment_text)}</p></div><button class="icon-danger" onclick="delComment(${x.id})">×</button></div>`).join(""):'<div class="empty">No discussion yet.</div>';document.getElementById("versions").innerHTML=versions.length?versions.map(x=>`<div class="version"><span class="version-no">v${x.version_number}</span><div><b>${esc(x.title)}</b><small>Changed by ${esc(x.changed_by_name)} · ${new Date(x.changed_at).toLocaleString()}</small><p>${esc(x.problem_statement)}</p></div></div>`).join(""):'<div class="empty">No previous versions yet. Edit the decision to create history.</div>'}
async function init(){requireLoginOrRedirect();document.getElementById("logout-btn").onclick=logout;if(!decisionId){document.getElementById("workspace").style.display="none";return}try{current=await apiRequest(`/decisions/${decisionId}`,{},true);document.getElementById("page-title").textContent="Decision Details";document.getElementById("title").value=current.title;document.getElementById("problem").value=current.problem_statement;document.getElementById("category").value=current.category||"";document.getElementById("status").value=current.status;document.getElementById("decision-status").textContent=current.status;document.getElementById("decision-status").className="status-badge "+current.status.toLowerCase().replaceAll(" ","-");document.getElementById("workspace").style.display="block";await loadAll()}catch(e){msg(e.message,"error")}}
document.getElementById("decision-form").onsubmit=async e=>{e.preventDefault();try{const body={title:title.value,problem_statement:problem.value,category:category.value||null,status:status.value};if(decisionId){await apiRequest(`/decisions/${decisionId}`,{method:"PUT",body:JSON.stringify(body)},true);msg("Decision updated. A new version was recorded.");await loadAll()}else{const d=await apiRequest("/decisions",{method:"POST",body:JSON.stringify(body)},true);location.href=`decision.html?id=${d.id}`}}catch(e){msg(e.message,"error")}}
document.getElementById("alt-form").onsubmit=async e=>{e.preventDefault();try{await apiRequest(`/decisions/${decisionId}/alternatives`,{method:"POST",body:JSON.stringify({title:document.getElementById("alt-title").value,description:document.getElementById("alt-description").value,pros:document.getElementById("alt-pros").value,cons:document.getElementById("alt-cons").value,estimated_cost:document.getElementById("alt-cost").value?Number(document.getElementById("alt-cost").value):null,feasibility:document.getElementById("alt-feasibility").value,risk:document.getElementById("alt-risk").value})},true);e.target.reset();msg("Alternative added.");loadAll()}catch(e){msg(e.message,"error")}}
document.getElementById("upload-form").onsubmit=async e=>{e.preventDefault();const f=document.getElementById("file").files[0];if(!f)return;const fd=new FormData();fd.append("file",f);try{const r=await fetch(`${API_BASE_URL}/documents/decision/${decisionId}`,{method:"POST",headers:{Authorization:`Bearer ${getToken()}`},body:fd});if(!r.ok){const x=await r.json();throw new Error(x.detail||"Upload failed")}e.target.reset();msg("Document uploaded.");loadAll()}catch(e){msg(e.message,"error")}}
document.getElementById("comment-form").onsubmit=async e=>{e.preventDefault();try{await apiRequest(`/decisions/${decisionId}/discussions`,{method:"POST",body:JSON.stringify({comment_text:document.getElementById("comment").value})},true);e.target.reset();msg("Comment posted.");loadAll()}catch(e){msg(e.message,"error")}}
async function delAlt(id){if(confirm("Delete this alternative?")){try{await apiRequest(`/decisions/alternatives/${id}`,{method:"DELETE"},true);loadAll()}catch(e){msg(e.message,"error")}}}
async function delDoc(id){if(confirm("Delete this document?")){try{await apiRequest(`/documents/${id}`,{method:"DELETE"},true);loadAll()}catch(e){msg(e.message,"error")}}}
async function delComment(id){if(confirm("Delete this comment?")){try{await apiRequest(`/decisions/discussions/${id}`,{method:"DELETE"},true);loadAll()}catch(e){msg(e.message,"error")}}}
init();
